import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

List<String> places = [
  'Coffee shop',
  'Table',
  'Bed',
  'Home Office',
  'Library',
  'Living Room',
  'School',
  'Office',
  'Other',
];


Map<String, Widget> placesAssetsLarge = {
  'Coffee shop': SvgPicture.asset("assets/svgs/coffee.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Table': SvgPicture.asset("assets/svgs/Table.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Bed': SvgPicture.asset("assets/svgs/Bed.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Home Office': SvgPicture.asset("assets/svgs/desk.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Library': SvgPicture.asset("assets/svgs/library.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Living Room': SvgPicture.asset("assets/svgs/livingroom.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'School': SvgPicture.asset("assets/svgs/school.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Office': SvgPicture.asset("assets/svgs/office.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/svgs/other.svg",
      height: 100,
      width: 100,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
};














Map<String, Widget> placesAssets = {
  'Coffee shop': SvgPicture.asset("assets/svgs/coffee.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Table': SvgPicture.asset("assets/svgs/Table.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Bed': SvgPicture.asset("assets/svgs/Bed.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Home Office': SvgPicture.asset("assets/svgs/desk.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Library': SvgPicture.asset("assets/svgs/library.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Living Room': SvgPicture.asset("assets/svgs/livingroom.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'School': SvgPicture.asset("assets/svgs/school.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Office': SvgPicture.asset("assets/svgs/office.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/svgs/other.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
};

Map<String, Widget> placesAssetsMini = {
  'Coffee shop': SvgPicture.asset("assets/svgs/coffee.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Table': SvgPicture.asset("assets/svgs/Table.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Bed': SvgPicture.asset("assets/svgs/Bed.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Home Office': SvgPicture.asset("assets/svgs/desk.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Library': SvgPicture.asset("assets/svgs/library.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Living Room': SvgPicture.asset("assets/svgs/livingroom.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'School': SvgPicture.asset("assets/svgs/school.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Office': SvgPicture.asset("assets/svgs/office.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/svgs/other.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
};

Map<String, Widget> placesAssetsMiniBlack = {
  'Coffee shop': SvgPicture.asset("assets/svgs/coffee.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Table': SvgPicture.asset("assets/svgs/Table.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Bed': SvgPicture.asset("assets/svgs/Bed.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Home Office': SvgPicture.asset("assets/svgs/desk.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Library': SvgPicture.asset("assets/svgs/library.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Living Room': SvgPicture.asset("assets/svgs/livingroom.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'School': SvgPicture.asset("assets/svgs/school.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Office': SvgPicture.asset("assets/svgs/office.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/svgs/other.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
};

List<String> subjects = [
  'Biology',
  'Chemistry',
  'Physics',
  'Maths',
  'History',
  'Geography',
  'English',
  'Economics',
  'Other',
];

Map<String, Widget> subjectAssets = {
  'Biology': SvgPicture.asset("assets/subjects/Biology.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Chemistry': SvgPicture.asset("assets/subjects/Chemistry.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Physics': SvgPicture.asset("assets/subjects/Physics.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Maths': SvgPicture.asset("assets/subjects/maths.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'History': SvgPicture.asset("assets/subjects/history.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Geography': SvgPicture.asset("assets/subjects/geography.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'English': SvgPicture.asset("assets/subjects/english.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Economics': SvgPicture.asset("assets/subjects/economics.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/subjects/other.svg",
      height: 50,
      width: 50,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
};

Map<String, Widget> subjectAssetsMini = {
  'Biology': SvgPicture.asset("assets/subjects/Biology.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Chemistry': SvgPicture.asset("assets/subjects/Chemistry.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Physics': SvgPicture.asset("assets/subjects/Physics.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Maths': SvgPicture.asset("assets/subjects/maths.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'History': SvgPicture.asset("assets/subjects/history.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Geography': SvgPicture.asset("assets/subjects/geography.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'English': SvgPicture.asset("assets/subjects/english.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Economics': SvgPicture.asset("assets/subjects/economics.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/subjects/other.svg",
      height: 30,
      width: 30,
      color: Colors.white,
      semanticsLabel: 'A red up arrow'),
};

Map<String, Widget> subjectAssetsMiniBlack = {
  'Biology': SvgPicture.asset("assets/subjects/Biology.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Chemistry': SvgPicture.asset("assets/subjects/Chemistry.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Physics': SvgPicture.asset("assets/subjects/Physics.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Maths': SvgPicture.asset("assets/subjects/maths.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'History': SvgPicture.asset("assets/subjects/history.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Geography': SvgPicture.asset("assets/subjects/geography.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'English': SvgPicture.asset("assets/subjects/english.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Economics': SvgPicture.asset("assets/subjects/economics.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
  'Other': SvgPicture.asset("assets/subjects/other.svg",
      height: 30,
      width: 30,
      color: Colors.grey,
      semanticsLabel: 'A red up arrow'),
};
